#!/bin/sh

# Don't run ci for main, master, maint, next, seen or "upstream" tags
case "$1" in
    refs/heads/main|refs/heads/master|refs/heads/maint|refs/heads/next|refs/heads/seen|refs/tags/gitgui-*|refs/tags/pr-[0-9]*|refs/tags/v[1-9].*)
	exit 1;;
    *)
	exit 0;;
esac
